[project]
name = "mcp-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire>=0.7.0",
    "huggingface-hub>=0.29.2",
    "mcp[cli]>=1.3.0",
]
